# Generated by Django 3.2.8 on 2021-10-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
