# Generated by Django 3.2.8 on 2021-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopizza', '0002_rename_toppings_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='djangopizza.Topping'),
        ),
    ]
